@RiverBooks = https://localhost:7180
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzcwMDIwMzksImlhdCI6MTczNjkxNTYzOSwiRW1haWxBZGRyZXNzIjoidGVzdDFAZ21haWwuY29tIiwibmJmIjoxNzM2OTE1NjM5fQ.9OLLk7jV4-DVx1qHJO6iUIAZXELZnAY_9F2IQ70h1_c

GET {{RiverBooks}}/books/
Accept: application/json

###
GET {{RiverBooks}}/books/32f56978-f320-4ad0-aea8-41a0e02d1d11
Accept: application/json

###
POST {{RiverBooks}}/books
Accept: application/json
Content-Type: application/json
{
  "title": "",
  "Author": "Gershy Menzer 2",
  "price": 14.00
}

###
DELETE {{RiverBooks}}/books/1b23ebac-9f38-4a77-8805-dcee6de2e4f5
Accept: application/json

###
POST {{RiverBooks}}/books/8105a275-4590-45c6-bffb-e2425aead681/priceHistory
Accept: application/json
Content-Type: application/json
{
  "id": "9568d213-73c3-442f-8843-57ab7819bb7a",
  "newPrice": 1.99
}

###
POST {{RiverBooks}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "Test123!"
}

###
POST {{RiverBooks}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "Test123!"
}

###
GET {{RiverBooks}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###
POST {{RiverBooks}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookId": "8105a275-4590-45c6-bffb-e2425aead681",
  "quantity": 1
}
